# Generated by Django 6.0.9 on 2026-10-06 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('home', models.CharField(blank=True, max_length=200, verbose_name='Home asked about')),
                ('message', models.TextField(max_length=3000)),
                ('sms_consent', models.BooleanField(default=False, verbose_name='Agreed to calls and texts')),
                ('sms_consent_text', models.TextField(blank=True, help_text='Exact consent wording shown when they agreed')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload a real photo. This is used when set.', upload_to='photos/')),
                ('unsplash_id', models.CharField(blank=True, help_text='Placeholder photo, e.g. photo-1568605114967-8130f3a36994. Used only when no image is uploaded.', max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(help_text='e.g. San Antonio, TX', max_length=120)),
                ('source', models.CharField(max_length=120, verbose_name='Where the discount came from')),
                ('nearby_price', models.PositiveIntegerField(help_text='What similar homes nearby sold for')),
                ('purchase_price', models.PositiveIntegerField()),
                ('costs', models.PositiveIntegerField(help_text='Refresh, closing, and holding costs')),
                ('sale_price', models.PositiveIntegerField()),
                ('bought', models.DateField()),
                ('listed', models.DateField()),
                ('sold', models.DateField()),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-sold'],
            },
        ),
        migrations.CreateModel(
            name='DealInProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload a real photo. This is used when set.', upload_to='photos/')),
                ('unsplash_id', models.CharField(blank=True, help_text='Placeholder photo, e.g. photo-1568605114967-8130f3a36994. Used only when no image is uploaded.', max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('stage', models.CharField(choices=[('offer', 'Offer accepted'), ('inspection', 'Inspection'), ('closing', 'Closing'), ('refresh', 'Light refresh'), ('photos', 'Listing photos'), ('listed', 'Listed')], default='offer', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=10, help_text='0 to 100')),
                ('expected_listing', models.CharField(help_text='e.g. December 2026', max_length=60)),
                ('update', models.TextField(verbose_name='Latest update')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'deal in progress',
                'verbose_name_plural': 'deals in progress',
                'ordering': ['order', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Used in the web address, e.g. 124-oakwood-lane', unique=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='TX', max_length=2)),
                ('price', models.PositiveIntegerField(help_text='Asking price in dollars')),
                ('nearby_price', models.PositiveIntegerField(help_text='What similar homes nearby recently sold for. Use real comparable sales.')),
                ('beds', models.PositiveSmallIntegerField()),
                ('baths', models.DecimalField(decimal_places=1, max_digits=3)),
                ('sqft', models.PositiveIntegerField(verbose_name='Square feet')),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('for_sale', 'For Sale'), ('under_contract', 'Under Contract'), ('coming_soon', 'Coming Soon'), ('sold', 'Sold')], default='for_sale', max_length=20)),
                ('source', models.CharField(help_text='e.g. Estate sale, Job relocation', max_length=120, verbose_name='Why it is priced lower')),
                ('summary', models.CharField(help_text='One line shown on the listing card', max_length=200)),
                ('description', models.TextField()),
                ('features', models.TextField(blank=True, help_text='One highlight per line')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers show first')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['order', '-created'],
            },
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload a real photo. This is used when set.', upload_to='photos/')),
                ('unsplash_id', models.CharField(blank=True, help_text='Placeholder photo, e.g. photo-1568605114967-8130f3a36994. Used only when no image is uploaded.', max_length=80)),
                ('alt', models.CharField(blank=True, help_text='Describe the photo for screen readers', max_length=200, verbose_name='Description')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.property')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
