# Generated by Django 6.0.9 on 2026-10-06 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='As the reviewer agreed to be shown, e.g. "Maria G."', max_length=80)),
                ('location', models.CharField(blank=True, max_length=80)),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', max_length=10)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='1 to 5, exactly as the reviewer gave it')),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('source', models.CharField(default='Google', help_text='Where the review was posted', max_length=40)),
                ('source_url', models.URLField(blank=True, help_text='Link to the original review so visitors can check it')),
                ('is_approved', models.BooleanField(default=False, help_text='Show on the site. Only approve genuine reviews; never write or edit them yourself.')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TrustProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, help_text='e.g. Thistledown Homes LLC', max_length=150)),
                ('entity_type', models.CharField(blank=True, help_text='e.g. Texas limited liability company', max_length=60)),
                ('filing_number', models.CharField(blank=True, max_length=40, verbose_name='Texas SOS file number')),
                ('formed_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('business_address', models.CharField(blank=True, max_length=200)),
                ('license_note', models.CharField(blank=True, help_text='e.g. "Not a licensed real estate agent" or your TREC license number if you get one', max_length=200)),
                ('title_companies', models.TextField(blank=True, help_text='Title companies you close with, one per line')),
                ('google_business_url', models.URLField(blank=True, verbose_name='Google Business Profile')),
                ('bbb_url', models.URLField(blank=True, verbose_name='Better Business Bureau profile')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'trust profile',
                'verbose_name_plural': 'trust profile',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='county_record_url',
            field=models.URLField(blank=True, help_text='Link to this property on the county appraisal district site, showing your company as owner.', verbose_name='County ownership record'),
        ),
        migrations.AddField(
            model_name='property',
            name='portal_url',
            field=models.URLField(blank=True, help_text='Link to the same home on a major listing site, once it is on the MLS.', verbose_name='Zillow / Realtor.com listing'),
        ),
        migrations.CreateModel(
            name='Comparable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('sold_date', models.DateField()),
                ('sold_price', models.PositiveIntegerField()),
                ('beds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('baths', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('sqft', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(default='MLS', help_text='Where the sale is recorded, e.g. MLS or County records', max_length=60)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparables', to='website.property')),
            ],
            options={
                'ordering': ['-sold_date'],
            },
        ),
    ]
