# Generated by Django 6.0.9 on 2026-10-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_review_trustprofile_property_county_record_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Map pin. In Google Maps, right-click the house and click the coordinates to copy them, e.g. 30.267153', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='e.g. -97.743057', max_digits=9, null=True),
        ),
    ]
