# Generated by Django 6.0.9 on 2026-10-06 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_property_latitude_property_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_label', models.CharField(help_text='Address at the time of the request', max_length=200, verbose_name='Home')),
                ('listed_price', models.PositiveIntegerField(help_text='Asking price at the time of the request')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('offer_price', models.PositiveIntegerField()),
                ('financing', models.CharField(choices=[('cash', 'Cash'), ('preapproved', 'Mortgage, already pre-approved'), ('mortgage', 'Mortgage, not pre-approved yet'), ('other', 'Other or not sure')], max_length=20)),
                ('lender', models.CharField(blank=True, max_length=120, verbose_name='Lender (if any)')),
                ('timeline', models.CharField(choices=[('asap', 'As soon as possible'), ('30', 'Within 30 days'), ('45', 'Within 45 days'), ('60', 'Within 60 days'), ('flexible', 'Flexible')], max_length=20, verbose_name='Closing timeline')),
                ('wants_showing', models.BooleanField(default=True, verbose_name='Wants a showing first')),
                ('has_agent', models.BooleanField(default=False, verbose_name='Working with an agent')),
                ('agent_name', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True, max_length=3000)),
                ('acknowledged', models.BooleanField(default=False, verbose_name='Acknowledged non-binding terms')),
                ('acknowledgement_text', models.TextField(blank=True, help_text='Exact wording they agreed to')),
                ('sms_consent', models.BooleanField(default=False, verbose_name='Agreed to calls and texts')),
                ('sms_consent_text', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('showing', 'Showing scheduled'), ('contract', 'Under contract'), ('closed', 'Closed'), ('declined', 'Declined or withdrawn')], default='new', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_requests', to='website.property')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
